### ISSUE TITLE
I'm willing to add a French translation

### ISSUE THREAD

**Issue by Funky3000** [nh-server/switch-guide#107]
Hi,

This may not be the most suitable place for that (some helpers from the NH discord server advised me to post here), but i've noticed that, compared to the 3DS  guide, there isn't any translation for the switch guide.

From what i've understood, as the 3DS guide was updated, translators didn't update their translations according to that, which is why there isn't any translation available for the switch guide.

If that's the case, i am fine with giving a proper french translation of the switch guide, along with keeping it updated (as long as i'm mentioned when the guide gets updated).

If by any chance you're interested in me giving a translation, then i would gladly accept.

Best regards.

**Comment by el-emmo** [comment]
We might consider it in the future, but currently there are no plans to maintain translated pages of the switch guide.
