### ISSUE TITLE
fusee-interface-tk 

### ISSUE THREAD

**Issue by FellFromTheSky** [nh-server/switch-guide#114]
Please add this to the guide :
fusee-interface-tk must be run as root on linux.

**Comment by dennthecafebabe** [comment]
1. ![image](https://user-images.githubusercontent.com/47433458/81431642-c4edde80-9161-11ea-9909-6db0710a2d07.png)
2. It doesn't technically need to be run as root, you can also create an udev rule for it (which I would recommend over sudo)

**Comment by dennthecafebabe** [comment]
Oh, I guess I should add an example for such a udev rule, this would be what I personally got:
```
$ cat /etc/udev/rules.d/70-swonch.rules 
ATTRS{idVendor}=="0955", ATTRS{idProduct}=="7321", MODE="666", GROUP="cafebabe"
```
Simply replace `cafebabe` with a group your user is part of and now you can push payloads without needing to sudo every time

**Comment by bleck9999** [comment]
The guide also has instructions for a udev rule (https://nh-server.github.io/switch-guide/extras/adding_udev/)

**Comment by FellFromTheSky** [comment]
Oh ok thanks.
I didn't saw it.
