### ISSUE TITLE
Switch Guide Suggestions

### ISSUE THREAD

**Issue by HeyItsIconic** [nh-server/switch-guide#118]
**1.** During SD Preparations, It should probably state in the guide that if your computer asks you to "merge" the two bootloader folders that it's totally fine to merge them. I'm sure most Switch Helpers have seen the question "it says to merge the Bootloader folders, is that okay?" or something like it enough times.
**2.** Regarding the SD Format warning, it states FAT32 is recommended, I think it should also explicitly say that exFAT is really not recommended due to how prone it is to corruptions (this is far more likely to incentivize people to do FAT32 > exFAT).
**3.** The part where it says "The SD Formatting should take about 5 minutes" should probably be reworded (akin to how the Boot0/1 thing was reworded) given TE is much faster now. A few people have come and asked something along the lines of "the guide says it should take 5 min but mine took ~30 is that okay?" 

Also this has nothing to do with the nh guide in particular but I figured I might as well chuck it on here cause yolo.
- Consider adding an invite link for the Edizon Discord Server (for Kurisu)

**Comment by thedax** [comment]
As these have been addressed by #119  and #120 , I will close this.
