### ISSUE TITLE
Updating disabled AutoRCM

### ISSUE THREAD

**Issue by BlastFurnaceNS** [nh-server/switch-guide#123]
Please include some reference on either (or both) but especially the "updating" page, to the fact that updating your stock FW disables AutoRCM, I no longer have a functioning jig, and I would not have updated if I had known that I would be losing AutoRCM, as I can no longer get into hekate.

Pages:
https://github.com/nh-server/switch-guide/blob/master/docs/extras/autorcm.md
https://github.com/nh-server/switch-guide/blob/master/docs/extras/updating.md

**Comment by el-emmo** [comment]
#124 

I don't think it's necessary on the autorcm page.

**Comment by suchmememanyskill** [comment]
#124 has been merged, closing issue
