### ISSUE TITLE
Launch Atmosphere FSS0 EmuMMC failed, says "emummc is forced but not enabled"

### ISSUE THREAD

**Issue by asingingfish** [nh-server/switch-guide#129]
I followed the instructions completely, but still failed...

All resources are using the latest release.

Is the `hekate_ipl.ini` file out date ?

**Comment by el-emmo** [comment]
No the hekate_ipl.ini is not outdated, that error means you’re trying to boot into an emuMMC while not actually having created one (or it’s not enabled).

**Comment by asingingfish** [comment]
I found that I was missing **the step of create emuMMC**...

thanks

**Comment by thedax** [comment]
Seeing as this has been resolved, I'll go ahead and close this.
