### ISSUE TITLE
Updating Atmosphere doesn't reset the settings

### ISSUE THREAD

**Issue by Araraura** [nh-server/switch-guide#145]
In the **Updating CFW** part of the guide, under the **Updating Atmosphere** part, it says:

`Copy the contents of the Atmosphere .zip file to the root of your SD card.
If you are prompted to overwrite files, do so, except for the .ini files.
If you do accidentally overwrite the .ini files, this is not an emergency but you will lose any changes you made to Atmospheres settings.`

However, it only replaces the files in `/config_templates`, not `/config`, so you're not actually replacing any of your current settings.

**Comment by suchmememanyskill** [comment]
Resolved in commit 5eab4df
