### ISSUE TITLE
Can't find any topic of what every joycon pin does

### ISSUE THREAD

**Issue by OscarLake** [nh-server/switch-guide#152]
Can't find any topic of what every joycon pin does, i'm looking for a alternate method of rcm... If the left joycon is connected on the rigth bay just rotating it and pressing some keys, are the only thing you need?

**Comment by eip618** [comment]
you seem to be posting an issue on github. 
this is not a good place to ask for assistance. 
there is no known alternative method of rcm at this time beyond temporarily removing some of the internal chips
