### ISSUE TITLE
Adding Hekate SD partition instructions

### ISSUE THREAD

**Issue by bela333** [nh-server/switch-guide#154]
The current SD partition instructions require the use of TegraExplorer even though Hekate has had the SD partition manager since  May 1 2020.

**Comment by suchmememanyskill** [comment]
What would be the reason to switch to hekate? Using hekate for partitioning means we need to restructure the guide, as hekate needs files on the sd for it's partitioner to work. This also means it's probably more error prone as people can forget the files

**Comment by bela333** [comment]
I thought Hekate only needs its own files in order for partitioning to work. As long as the files on the SD card don't exceed a certain size limit, they will be automatically restored after the partitioning anyway.
I would argue having to use less tools would make the guide easier.

**Comment by suchmememanyskill** [comment]
I think the guide starting at payload injection is a good thing, as that instantly tests patched switches. You can't do that with the hekate partitioner, as it needs it's files.

Also, yes hekate backs up 1gb then restores it after partitioning, but usually people have nintendo folders and stuff on their sd, so they have to move everything off anyway

**Comment by el-emmo** [comment]
Closing this, the guide will continue using TegraExplorer because of what suchmeme said above.
