### ISSUE TITLE
After extracting a save, how can I import it to a new switch?

### ISSUE THREAD

**Issue by josegonzalez** [nh-server/switch-guide#175]
I am attempting to recover saves from a corrupt emmuMMC install. I'm able to follow the guide [here](https://suchmememanyskill.github.io/guides/switchextractsaves/) to get the saves from the emmuMMC, but after that it's unclear what I should do to use those saves on a new emmuMMC partition.

Is there a way to do the above? I don't know if it's as simple as just rewriting the save directory or if I'm missing something critical here.

**Comment by eip618** [comment]
this is not an issue. you are seeking assistance.
try https://discord.gg/nintendohomebrew

**Comment by josegonzalez** [comment]
Apologies. Thanks for the link :)
