### ISSUE TITLE
Do I need to update CFW and sysMMC in a particular order?

### ISSUE THREAD

**Issue by FieryMewtwo** [nh-server/switch-guide#180]
I would ask at Atmosphère's repo, but since the guide has you set up things in an unorthodox way, I figured I should ask here.

(Also I had sigpatches and they aren't well liked over there.*)

* not for piracy, just thought I needed them, turned out I didn't, and now they're here to stay because I'm too lazy to figure out how to remove them.

**Comment by el-emmo** [comment]
Please do not use the issues tab as a support forum.

If you need help with the guide use the Nintendo Homebrew Discord server.

(Also, depending on how you're using them, we also consider sigpatches piracy.)

**Comment by FieryMewtwo** [comment]
I thought I needed them to dump my gamecarts. (yes I'm a noob.)
