### ISSUE TITLE
Updated emu_boot.bmp

### ISSUE THREAD

**Issue by HenryBaby** [nh-server/switch-guide#187]
Hullo, not sure where to put this. I just made this for myself, I felt like the emu_boot was a bit outdated. Thought I'd share if it's something you lot would like to use

![image](https://user-images.githubusercontent.com/7832145/162226073-8de5933d-d386-4065-815d-d542e3b7fb32.png)
[emu_boot.zip](https://github.com/nh-server/switch-guide/files/8443967/emu_boot.zip)
Github converts it to a png, and doesn't allow me to upload .bmp formats, so here it is in a zip archive :)

**Comment by el-emmo** [comment]
We think it would look better if the SD text in the middle was either centered or just removed entirely.

**Comment by HenryBaby** [comment]
I made two versions :)

![image](https://user-images.githubusercontent.com/7832145/162486349-b721cd26-df88-4523-87b8-e7d6c763a3bc.png)
![image](https://user-images.githubusercontent.com/7832145/162486374-ad1f7325-8a32-4b24-a446-833fcc776f25.png)
[emu_boot.zip](https://github.com/nh-server/switch-guide/files/8453944/emu_boot.zip)

**Comment by el-emmo** [comment]
Hi, sorry for the late reply. As per #191 emummc is logo is now the one with the SD text on top. 
Thank you for the contribution!
