### ISSUE TITLE
New installer packages both games and Payload

### ISSUE THREAD

**Issue by riz7861** [nh-server/switch-guide#197]
New installer called NS Usb Loader packages both the installation of the payload (S) and the installation of games with twinwoo

https://github.com/developersu/ns-usbloader

**Comment by bleck9999** [comment]
ok and?

**Comment by riz7861** [comment]
Sorry, I wanted to add this to the guide as it makes life easier for us all. Tested the app on Linux windows and Mac. It has in built tools to install the drivers.

**Comment by riz7861** [comment]
I've raised this In the wrong place haven't I.

**Comment by riz7861** [comment]
Non issue
