### ISSUE TITLE
Who should I talk to about getting unbanned from the Discord server?

### ISSUE THREAD

**Issue by chexo3** [nh-server/switch-guide#203]
I don't remember when or why I got banned. I don't have a username for an admin or else I'd send a friend request and reach out that way. I'd like to rejoin.

**Comment by eip618** [comment]
1. sir, this is a ~~wendy's~~ github issues section
2. we have a website: https://nintendohomebrew.com
3. we have an email: staff@nintendohomebrew.com

**Comment by chexo3** [comment]
I only knew about the GitHub pages site I’m sorry

**Comment by chexo3** [comment]
check your email please @eip618
