### ISSUE TITLE
Remove unnecessary lines from hekate_ipl.ini and improve config readability 

### ISSUE THREAD

**Issue by Sanrax** [nh-server/switch-guide#205]
Currently, this is the config being used:
```
[config]
updater2p=1
{------ Atmosphere ------}
[Atmosphere FSS0 EmuMMC]
fss0=atmosphere/package3
kip1=atmosphere/kips/*
emummcforce=1
icon=bootloader/res/emu_boot.bmp
{}
[Atmosphere FSS0 SYS]
fss0=atmosphere/package3
kip1=atmosphere/kips/*
emummc_force_disable=1
icon=bootloader/res/sys_cfw_boot.bmp
{}
{-------- Stock ---------}
[Stock SYS]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1
icon=bootloader/res/stock_boot.bmp
```

The kip1 line found in both FSS0 sections is completely useless and does nothing. The folder it's pointing to doesn't exist, so why is that line still there?

Next, the spacing makes this file really confusing to read at first glance. Why are we using `{}` instead of just a blank line to separate sections? This is completely supported by Hekate.

Also, the naming scheme is inconsistent. We have ` Atmosphere FSS0 SYS` and `Atmosphere FSS0 emuMMC`. Sys is also an emmc chip, so wouldn't it be more appropriate to have it say `Atmosphere FSS0 sysMMC` to match the naming of emu?

This is an example of my proposed config, and what I personally use:

```
[config]
autoboot=0
autoboot_list=0
bootwait=3
autohosoff=0
autonogc=0
updater2p=1
backlight=100

[Atmosphere FSS0 emuMMC]
fss0=atmosphere/package3
emummcforce=1
icon=bootloader/res/emu_boot.bmp

[Atmosphere FSS0 sysMMC]
fss0=atmosphere/package3
emummc_force_disable=1
icon=bootloader/res/sys_cfw_boot.bmp

[Stock sysMMC]
fss0=atmosphere/package3
emummc_force_disable=1
stock=1
icon=bootloader/res/stock_boot.bmp
```

**Comment by oreo639** [comment]
`kip1=atmosphere/kips/*` is correct.
Hekate bypasses Atmosphere's `fusee.bin` so the kip1 option is used to provide some amount of feature parity (i.e. for support issues).
https://github.com/Atmosphere-NX/Atmosphere/blob/e54957285f4ab97003e500b2475bf132976e0645/fusee/program/source/fusee_stratosphere.cpp#L765

> autoboot=0
> autoboot_list=0
> bootwait=3
> autohosoff=0
> autonogc=0
> backlight=100

Ofc don't add these, we only have `updater2p=1` to avoid inconsistencies in reboot to payload.

Changing `SYS` to `sysMMC` is fine though if you want to PR that.

**Comment by oreo639** [comment]
I assume this is resolved now with https://github.com/nh-server/switch-guide/pull/206?

**Comment by Sanrax** [comment]
Correct. Closing now.
