### ISSUE TITLE
typos in the guide

### ISSUE THREAD

**Issue by Mulderd015** [nh-server/switch-guide#35]
"Download the atmosphere-(version).zip **relese** of Atmosphere."
relese should be release.

locations: 
- switch-guide/docs/user_guide/emummc/sd_preparation.md
- switch-guide/docs/user_guide/sysnand/sd_preparation.md

"a smaller **amout** of available memory"
amout should be amount.

locations:
- switch-guide/docs/user_guide/emummc/launching_cfw.md
- switch-guide/docs/user_guide/sysnand/launching_cfw.md

"launch the Homebrew Menu by **by** holding the R button"
remove the second by

locations:
- switch-guide/docs/user_guide/emummc/launching_cfw.md
- switch-guide/docs/user_guide/sysnand/launching_cfw.md

**Comment by suchmememanyskill** [comment]
Fixed in latest commit, thanks
