### ISSUE TITLE
Potentially outdated information about EmuNAND in the FAQ

### ISSUE THREAD

**Issue by JJJollyjim** [nh-server/switch-guide#41]
(I'm a first-time prospective switch hacker so don't feel comfortable wording the relevant changes in a pull request, so just suggesting what I think is an issue)

---

The "Is it safe to use homebrew?" section in the FAQ talks about EmuNAND as a thing that may be developed in the future.

> In a future Atmosphere update, we will be able to create a dual-boot (EmuNAND) solution, that allows us to have a clean, online firmware and a seperate offline firmware for homebrew related software.
> [...]
>
>### SX OS
>
>Team Xecuter's "EmuNAND" is not a proper (or safe) EmuNAND, and Nintendo can pick up on it with their telemetry.

As I understand it, there is now a "true" EmuNAND solution integrated in Atmosphere, and if you follow the recommended path in the guide, that's what you'll end up with.

**Comment by noirscape** [comment]
The SX OS paragraph still holds true for what it's worth. This is because it mounts the partition the emuMMC is located on, regardless of partition or filebased to my knowledge.

The first paragraph does need updating, you are correct there.

**Comment by dennieh** [comment]
That paragraph got updated so this should be ready to close
