### ISSUE TITLE
patch test should refer to separate page

### ISSUE THREAD

**Issue by Mulderd015** [nh-server/switch-guide#44]
On the getting started page there is a link to test if you're patched
> If you are unsure if your serial is patched, you can test your console yourself following the instructions **here**.

The link goes to the sending payload step, but after testing the switch the user continues to the **Making the emuMMC** page. They should be brought back to the **Getting started** or **RCM** step. Otherwise they skip the partitioning and file preparation step.

**Comment by dennieh** [comment]
This was discussed a while ago and a separate page is not really desired.
I added a extra note at the top of the sending_payload page to redirect them if they got sent there to test their switch, that should be enough i think

![image](https://user-images.githubusercontent.com/47433458/62758129-c6c52d00-ba7d-11e9-8f39-4881a42f760e.png)
