### ISSUE TITLE
why not make the big pin be marked as 7

### ISSUE THREAD

**Issue by ImUrX** [nh-server/switch-guide#48]
![Pinout Charger Joycon](https://nh-server.github.io/switch-guide/user_guide/img/entering_rcm_solder_numbered.jpg)
as the titles says the big pin in the upper part is directly connected to 7 why not mention it everywhere where its easier to use that, its a lot more easy to solder to.

**Comment by ImUrX** [comment]
will make a PR if its a good idea, will not if someone mentions whats wrong in using it

**Comment by suchmememanyskill** [comment]
I'm not completely sure what you mean, you mean that this exact image is used multiple times across multiple joycon modding methods?

**Comment by ImUrX** [comment]
!(Example)[https://i.imgur.com/OGzf0Pa.png] This is what im trying to say
basically

**Comment by ImUrX** [comment]
!(Example)[https://i.imgur.com/OGzf0Pa.png] This is what im trying to say (I forgot emails didnt support markdown lel)

**Comment by ImUrX** [comment]
they are the same and make the mod a lot easier to do tbh, because sometimes when you solder the 7th pin, you mix it with a pin around it.

**Comment by NovaPhoenix** [comment]
Issue stagnated, our current solution seems to work fine. Closing.
