### ISSUE TITLE
Another 404 link in the FAQ

### ISSUE THREAD

**Issue by NightYoshi370** [nh-server/switch-guide#52]
https://nh-server.github.io/switch-guide/faq/#my-homebrew-is-not-showing-up-on-the-menu
When clicking the "Sending Payload" link, it returns a 404 page.

I wasn't sure if I should open a new issue or not. Sorry

**Comment by thedax** [comment]
This was fixed in https://github.com/nh-server/switch-guide/commit/8c16b7c4329693fe17d90d86d01ae9825fbf481a , so closing.
