### ISSUE TITLE
Page Request: File Types and Software Types

### ISSUE THREAD

**Issue by thecogdoctor** [nh-server/switch-guide#7]
Love the guide but I feel there are some holes in documentation in terms of the various types of software and file types used by CFW. (An index of abbreviations and terminology separate of the pages where they are used would also be a useful addition.)
My proposal;
- An index of filetypes used by the most commonly used and safest software 
    - (up to the admins/contributor's of course.
    - Usage and composition of file types including what programs use/support them.
- An index of software types used as custom firmware and or programs that support the loading of custom firmware.
  - This will not be an all encompassing list but a resource for the most reliable and we'll maintained software available.
   - Any software explicitly for piracy, software with frustrating anti-features, programs which may cause damage to the console or programs that put the user at risk of receiving a ban from Nintendo online services (for ex. SX OS for piracy, ReNiX for risk of console banning, etc) may be included at contributors discretion but must include a disclaimer above it state any of the aforementioned issues.
Cheers.

**Comment by noirscape** [comment]
> - An index of filetypes used by the most commonly used and safest software 

See [this](https://nh-server.github.io/switch-guide/faq/#what-formats-can-homebrew-come-in-where-do-i-place-my-downloaded-homebrew) FAQ entry, which I believe covers this suggestion already.

> - An index of software types used as custom firmware and or programs that support the loading of custom firmware. 

Unclear what you're exactly asking. If you're looking for an index of available Homebrew, I personally recommend to check out [SwitchBru](https://www.switchbru.com/appstore/#/) instead, maintaining such a thing here would clutter and be out of the scope of this guide.

The software used to push payloads is linked in the relevant sections.

> - Any software explicitly for piracy, software with frustrating anti-features, programs which may cause damage to the console or programs that put the user at risk of receiving a ban from Nintendo online services (for ex. SX OS for piracy, ReNiX for risk of console banning, etc) may be included at contributors discretion but must include a disclaimer above it state any of the aforementioned issues.

I am unware if you are in Nintendo Homebrew or not, but do realize that their piracy rules are incredibly strict and this runs directly contrary to these rules. There are already warnings in the [FAQ](https://nh-server.github.io/switch-guide/faq/#is-it-safe-to-use-homebrew-or-will-i-get-banned) for common ban causes and a warning about running random files (console damage) is included [here](ttps://nh-server.github.io/switch-guide/faq/#what-formats-can-homebrew-come-in-where-do-i-place-my-downloaded-homebrew).

**Comment by thecogdoctor** [comment]
> Unclear what you're exactly asking. If you're looking for an index of available Homebrew, I personally recommend to check out [SwitchBru](https://www.switchbru.com/appstore/#/) instead, maintaining such a thing here would clutter and be out of the scope of this guide.

That is the exact opposite of my intent with this section. I understand your earlier points, so rather than being a full index I would substitute an index of the different types of homebrew currently available. This includes information like, what this category of homebrew typically change and what files the most commonly used programs from these categories would use. 

> I am unware if you are in Nintendo Homebrew or not, but do realize that their piracy rules are incredibly strict and this runs directly contrary to these rules. There are already warnings in the [FAQ](https://nh-server.github.io/switch-guide/faq/#is-it-safe-to-use-homebrew-or-will-i-get-banned) for common ban causes and a warning about running random files (console damage) is included here.

I would like to revise this proposal in that case. Piracy would be explicitly disallowed from this list. Pointing me to the FAQ does me no benefit and accomplishes nothing. I have read the FAQ and understood it's contents. It's inadequacy is part of the reason I made this page request.

> See [this](https://nh-server.github.io/switch-guide/faq/#what-formats-can-homebrew-come-in-where-do-i-place-my-downloaded-homebrew) FAQ entry, which I believe covers this suggestion already.

That section covers 2 file types both of them not explained in terms of how they provide the content they deliver (and optionally, what software supports these filetypes). Again, the major reason I  made this post was due to the information provided in the FAQ was not sufficient.

I will be making a basic page example at some point to demonstrate my intent through more tangible means.

**Comment by thecogdoctor** [comment]
> 
> 
> > That section covers 2 file types both of them not explained in terms of how they provide the content they deliver (and optionally, what software supports these filetypes). Again, the major reason I made this post was due to the information provided in the FAQ not being sufficient for users more interested in the technical nature of homebrew.
> 
> There are no other filetypes for Homebrew applications that don't carry massive ban risks (the only type not listed is NSP which A. requires non-bundled patches onto Atmosphere and B. is ban-bait since this fucks up telemetry). Users more interested in the technical nature of Homebrew can check out ReSwitcheds website which has it's own [FAQ](https://reswitched.team/faq/) about the internals of the Nintendo Switch.
> 
> This guides FAQ details that NRO files are homebrew that is found on the home menu, while KIP files provide system services. To me this is an adequate explanation for beginning users.
> 
> Users that desire more technical information can refer to either [Switchbrew](https://switchbrew.org/wiki/Main_Page) or the aforementioned RS FAQ.

Awesome, thanks for those links! These address a lot of my concerns and ideas I was looking for. Maybe instead of my direct suggestions, a link to these websites would definitely benefit. I appreciate the direction. I made this suggestion as a way of ensuring those who are new get a few more of those details. Cheers.

**Comment by thecogdoctor** [comment]
Feel free to close this issue if it's been addressed fully.
