### ISSUE TITLE
90DNS changes

### ISSUE THREAD

**Issue by aveao** [nh-server/switch-guide#71]
Hello!

90dns got a USA instance today.

Similarly, the previous secondary instance (45.248.48.62) has been down for a while (which, I'll repeat from the repo: "If you have Adran's instance added as your secondary, then you have nothing to fear regarding bans, as if it can't connect to DNS, it'll simply fail instead of sending your data to Nintendo. However, I do recommend switching it to an active instance.").

Old secondary needs to be removed, and USA one should be included instead.

I'd edit it myself but the fact that there's an image and that I'm not sure how I should word the "use USA as primary if you're in americas, use france as primary if you're not, use the one that's not primary as your secondary" sentence in a way that'd be simple enough for this guide's purposes.

Relevant file is: docs/extras/blocking_updates.md
More information is in the commit: https://gitlab.com/a/90dns/commit/c70755967552871b65439a1c3f7dca71d10fc5ad

Thanks.

**Comment by noirscape** [comment]
~~we could try geolocation js for this~~

**Comment by SCOTT0852** [comment]
bold of you to forget about vpns
I'd put 2 different things, one saying "follow this if you're closer to america" and another saying "follow this if you're closer to france".

**Comment by dennieh** [comment]
Why not just say America and Europe? Or are there many locations that are closer to France than America but are not closer to Europe?

**Comment by aveao** [comment]
Yeah, that works. I'm just being super open about details so that people can have better information on what they're doing.

**Comment by dennieh** [comment]
Yeah, that makes sense. I'm unsure about the wording of it too, my line of thought would be changing [blocking_updates.md](https://raw.githubusercontent.com/nh-server/switch-guide/master/docs/extras/blocking_updates.md) to something along the lines of:
```
### Instructions

!!! tip ""
    1. Go to the Settings applet, and then to the Internet tab.
    2. Select the WiFi network you are connected to and click `Change Settings`.
    3. Change DNS Settings to Manual.
    4. For your Primary DNS pick the closest server out of the below chart.
    5. For your Secondary DNS pick any of the other out of the below chart
    6. Save Settings and test connection.
   
Server Location                 | Primary DNS       |
:-------------------------------|:------------------|
Europe (located in France)      | `163.172.141.219`       
America (located in the USA)    | `207.246.121.77`    


!!! tip ""
    ![Visual for System Settings serial location](../extras/img/blocking_updates.jpg)
```

This will look like this in the end 
![image](https://user-images.githubusercontent.com/47433458/66070567-d890f100-e551-11e9-8ed6-8af44b9e1ef5.png)

Would appreciate input on this as, as i said, I'm not really sure on the wording myself.

**Comment by aveao** [comment]
Looks good, perhaps something like:

```
Server Location                 | Primary DNS       |Secondary DNS       |
:-------------------------------|:------------------|:------------------|
Europe (located in France)      | `163.172.141.219`       | `207.246.121.77`
America (located in the USA)    | `207.246.121.77`    | `163.172.141.219`

```

would be easier to understand though

Also image could use an update too

**Comment by dennieh** [comment]
You're right, sounds way better that way. Image will definitely need a update, yeah. 
I can do that later today (~3-5 hours), i just don't have Wifi here so maybe someone else wants to do it instead.

**Comment by dennieh** [comment]
Yeah, this should be resolved now.
