### ISSUE TITLE
Easier steps for sd partitioning.

### ISSUE THREAD

**Issue by MrThanasiz** [nh-server/switch-guide#72]
At first i had to calculate the size of the first partition myself (to be the full size of the sd - 29872 - 16), changing the Unallocated Space Before & After only affected each other and not the size of the partition itself.

I thought that it would be easier to start from the last partition & go back to the middle one, so i came up with these steps:

-------------------------------------------------------------------------------------------------------
4. Create a new partition by right clicking on the unallocated space and then pressing `Create` with the following instructions:
	- Set metrics on the right of `Unallocated Space Before` and `Unallocated Space After` to MB if it's set to GB
	- Set the `File System` to `Unformated`
	- Set the partition size to `29872`
	- Set the `Unallocated Space After` to `0`

5. Create another new partition with the following settings:
	- Ignore the warning about windows not being able to recognize the partition
	- Set the file system to FAT32
	- Set the `Partition Label` to `SD`
	- Set the partition size to be the rest of the SD card space minus 16MB
	- Set the `Unallocated Space Before` to `16`
-------------------------------------------------------------------------------------------------------

Note: Screenshots would need an update & maybe the other OS instructions.

**Comment by PhazonicRidley** [comment]
Mini tool can be iffy if you don't do the 16 mb partition first sadly.

**Comment by suchmememanyskill** [comment]
Sd partitioning got easier due to us implementing TegraExplorer, a payload based file manager, into the guide. Minitool is no longer needed
