### ISSUE TITLE
Dead link on the updating guide

### ISSUE THREAD

**Issue by iomintz** [nh-server/switch-guide#83]
https://nh-server.github.io/switch-guide/extras/updating/
links to
https://nh-server.github.io/user_guide/sysnand/making_essential_backups/
which 404s.

**Comment by Oreo639** [comment]
Ty for reporting. It should be fixed with https://github.com/nh-server/switch-guide/commit/3c15b636ab6618fbd50a65ac4c02f941da20c3f3
