### ISSUE TITLE
Lockpick homebrew is deprecated 

### ISSUE THREAD

**Issue by shchmue** [nh-server/switch-guide#85]
I just noticed this recommends running Lockpick_RCM then Lockpick, but the latter isn’t necessary: https://nh-server.github.io/switch-guide/extras/dumping_title_keys/

**Comment by dennthecafebabe** [comment]
Sorry that no one has responded yet, it probably drowned in some other messages in the channel with the webhook. I bumped it now so they'll very likely see it :)

**Comment by NovaPhoenix** [comment]
Done, apologies for the delay

**Comment by shchmue** [comment]
Looks like it’s still talking about using the homebrew which isn’t necessary

**Comment by NovaPhoenix** [comment]
Your browser's cache hasn't updated, clear it and it should show the new contents

**Comment by shchmue** [comment]
I didn’t check the webpage, I looked at the commit. https://github.com/nh-server/switch-guide/commit/c4a638620c01ad47268c0a843d4716ad1fd84576

**Comment by NovaPhoenix** [comment]
Apologies, apologies, I don't know how I missed that, fixed it now

**Comment by shchmue** [comment]
I’d probably mention the titlekeys file will be in there too but otherwise good
