### ISSUE TITLE
I made a batch file that automates the steps of SD preparation

### ISSUE THREAD

**Issue by sttng** [nh-server/switch-guide#87]
As title - I made a batch file to automate the SD preparation.

It basically creates a folder (sd_prep) and puts all the stuff there. After you can just copy the contents of the folder into the root of your SD. Works under latest Win 10 (the one which includes curl and tar -  starting with Windows 10 build 17063 and later.)

https://github.com/sttng/nx-stuff/blob/master/sd_prep.cmd

**Comment by noirscape** [comment]
Couple of issues:

- Incognito is bad.
- nxdumptool and choidujournx aren't a part of the guide.
- We'd rather not automate the SD prep step, it's important for users to know what they're setting up. Black box approaches like these are incredibly unhandy for beginning users who are figuring out what they installed and what program each folder belongs to.

So while I'm sure it's neat, it's not going to be all that useful nor do I think we'll implement something like this in our guide.

**Comment by sttng** [comment]
First thanks for the quick reply! Appreciated!

1) might elaborate why Incognito is bad ?
2) Can understand the reason NXDumpTool is not added, but suggest ChoiDujourNX should be regardless of the batch file. 
3) I understand that doing everything manually is good for learning and understanding. On the other hand a batch file is easy to be read and edited as well.

**Comment by dennthecafebabe** [comment]
1. 
    a) Incognito itself is a interesting approach to avoiding telemetry, but as Adubbz 
    and SciresM said in ReSwitched once: we know that other services seem to be
    caching console-unique parts of PRODINFO and this was something that never 
    really got looked into apparently. 

    b) Homebrew itself should generally not modify the system's contents in a   
    unrecoverable way (with the only way to revert it is having a copy of the previous 
    data). Since there is a potential point-of-no-return we don't feel confident assisting 
    people with that software.

2. I personally don't feel too confident adding ChoiDujourNX to a general purpose sd 
    zip as:
    a) ChoiDujourNX doesn't generate the 8000...012 save properly (It strips the 
    ContentMetaAttributes when generating the IMKV). This might potentially be 
    picked up in telemetry, or can be in the future, so using ChoiDujourNX bears 
    a certain ban risk if not used properly (which would be offline-emummc-only).

    b) Putting in ChoiNX without disclaimers might tempt people to downgrade.

    So general i'd prefer ChoiNX to be it's own guide, with separate dedicated 
    warnings/disclaimers/instructions.

3. You really think that most users of your script would actually understand it?
    For them it will be a black box, they run it, it gives them files, done. But let's say 
    now that, hypothetically, in the future hekate was discontinued and we would need 
    a different chainloader now. Any person using your script will continue using it - it
    might break, or not, and they won't even notice it - while our guide shows people 
    where to find the source (no pun intended) of the tools they're using. There they 
    can see themselves what still is supported, and what isn't. After all, this here is 
    called a *guide*. :P

**Comment by sttng** [comment]
1) Ok I got it. Seems a valid approach. Then on the other hand any Homebrew which needs to go online should be taboo (such as an internet browser) unless something like 90dns is trusted. 

2) Is there another way then ChoiDujourNX to upgrade EmuMMC ? This would be the only reason to add it. I feel to upgrade sys first and then create a new emu based on sys too cumbersome. 

3) I think the Homebrew user of whom a certain technical affinity is expected could understand a batch file (even so I admit this particular one is not that straight forward). Still I mean it is expected of users to solder their own RCM rugs as if this guide. Agree that the batch file would need to be updated as the guide would be in case of any changes of softwares etc.

**Comment by TheGinGear** [comment]
1: Going online with homebrew is just fine, there isn't a ban risk. Using homebrew online in emuMMC with 90dns is already in the guide

2: There isn't any real reason to update your emuMMC for the vast majority. For the few who do, they have the seperate page of how to update the emuMMC. Prioritizing convenience of the few inconveniences the many here

3: They are not. Trust me, being in the assistance channels, half the people don't know how to open a bloody zip. On windows 10. I am not exaggerating, I have had to tell people to take files out of the zip, and explain what a zip is, countless times.

Also most people don't solder, they just buy a jig. Or jam a paperclip in.

**Comment by sttng** [comment]
3) Haha. Wouldn’t for those people who can’t even open a zip file on Win10 a fully automated Skript better :-P ?

**Comment by el-emmo** [comment]
If you don’t know how to open and copy files from a zip file you shouldn’t be trying to hack or modify your console.

**Comment by Oj18** [comment]
Also just to mention, any reason why not to just use [SDSetup](https://sdsetup.com) @sttng?

**Comment by sttng** [comment]
Didn’t know about SDSetup at the time.

**Comment by NovaPhoenix** [comment]
Issue has run its course, closing.
